#!/bin/bash

toggle_floating_key="Super_L+g"
last_window=$(wmctrl -lpx | tail -n1)
checked_window=$last_window
bash -c "$1"
while [[ $last_window == $checked_window ]]
do
	checked_window=$(wmctrl -lpx | tail -n1)
	echo "checked window $checked_window"
	sleep 0.1
done
window=$(wmctrl -lpx | tail -n1)
a=( $window )
wid=${a[0]}

echo $window

xdotool windowfocus --sync ${wid}
sleep 0.1
xdotool key ${toggle_floating_key}
sleep 0.1
wmctrl -ir ${wid} -b remove,maximized_horz
wmctrl -ir ${wid} -b remove,maximized_vert
sleep 0.1
xdotool windowsize --sync ${wid} ${4}% ${5}%
xdotool windowmove --sync ${wid} ${2} ${3}
sleep 0.1
xdotool mousemove  --sync $((${2} + 50)) $((${3} + 50))
xdotool windowfocus --sync ${wid}
echo ""
